## Settings affecting Tumblr
Tumblr:
    PostsPerPage: 10

# This allows the thimblr server to open your chosen editor to edit
# the theme you're currently viewing. There is a (very small!) risk
# that this could do malicious things, so you can disable it if you
#Â like
AllowEditing: true
# The editor you want to use for editing your themes. Below should
# be what you'd use if you were launching it from the command line
Editor: mate